### ISSUE TITLE
20230925 review

### ISSUE THREAD

**Issue by init** [KolobokMysnoy/HighLoad-VoiceAssistant#1]
20230925 Глобальная балансировка

1.  нет обоснования оптимальности расположения (вызывает вопросы наличие Питера и отсутствие Екатеринбурга/Новосибирска)
2. не хватает оценки влияния расположения ДЦ на продуктовые метрики (тут не давал таблиц и методик но подумайте)
3. не хватает расчёта нагрузки приходящейся на каждый ДЦ (это нужно будет в конце)
4. Anycast непонято как у вас рабтает если в регионе только один ДЦ, в любом случае нужна схема весов и помните что вам придется делать свою AS из-за этого решения
5. не раскрыта балансировка мобильных операторов (макрорегионы, по геобазе или в один из региона или в РФ, это я не читал, надо детально рассказывать конечно, добавлю в следующий прогон, пока на консультации расскажу)

**Comment by KolobokMysnoy** [comment]
1. Добавил учёт плотности населения + зависимость от магистральных линий связи.
2-3. Добавил нагрузку в RPS на каждый дата центр и количество пользователей. 
4. Я написал в финале главы, что поможет сократить время для подключения, что поможет увеличить время работы сервера без задержек для пользователя.
5. Тут хотел узнать, если использовать Latency-baced DNS, нужно ли проверять операторов мобильной связи? Ну и проблема с Москвой и Питером, их можно же решить только BGP Anycast, или как то ещё?
